export const states = {
  'ac': 'Acre',
  'al': 'Alagoas',
  'ap': 'Amapa',
  'am': 'Amazonas',
  'ba': 'Bahia',
  'ce': 'Ceara',
  'df': 'Distrito Federal',
  'es': 'Espírito Santo',
  'go': 'Goiás',
  'ma': 'Maranhão',
  'mt': 'Mato Grosso',
  'ms': 'Mato Grosso do Sul',
  'mg': 'Minas Gerais',
  'pa': 'Pará',
  'pb': 'Paraíba',
  'pr': 'Paraná',
  'pe': 'Pernambuco',
  'pi': 'Piauí',
  'rj': 'Rio de Janeiro',
  'rn': 'Rio Grande do Norte',
  'rs': 'Rio Grande do Sul',
  'ro': 'Rondônio',
  'rr': 'Roraima',
  'sc': 'Santa catarina',
  'sp': 'São paulo',
  'se': 'Sergipe',
  'to': 'Tocantins'
}